<?php

namespace Tests\Unit;

use App\Breed;
use App\Contracts\BreedContract;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class BreedTest extends TestCase
{
    /**
     * @var BreedContract
     */
    private $breedContract;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->breedContract = app(BreedContract::class);
    }

    public function testGetById()
    {
        $breedExpected = Breed::where('breed_id', 'beng')->first();
        $breed = $this->breedContract->getByName('bomb');

        $this->assertEquals($breedExpected, $breed);
    }
}
